---
- name: copy uwsgi config file to /etc/uwsgi-emperor/vassals/
  become: yes
  copy:
    src: files/vassals
    dest: "/etc/uwsgi-emperor/"

- name: copy uwsgi ini file to /etc/uwsgi-emperor/
  become: yes
  copy:
    src: files/emperor.ini
    dest: "/etc/uwsgi-emperor/"

- name: copy nginx config file to /etc/nginx/sites-enabled
  become: yes
  copy:
    src: files/huddlemoneytesthttp.conf
    dest: "/etc/nginx/sites-enabled"

- name: install uwsgi init script
  become: yes
  copy:
    src: files/uwsgi-init.d/uwsgi-emperor
    dest: "/etc/init.d/uwsgi-emperor"
    owner: root 
    group: root 
    mode: 0755

- name: install uwsgi default config
  become: yes
  copy:
    src: files/uwsgi-default/uwsgi-emperor
    dest: "/etc/default/uwsgi-emperor"
    owner: root 
    group: root 
    mode: 0640

- name: enable uwsgi service
  become: yes
  service:
    name: uwsgi 
    enabled: yes

